<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Activite extends \App\Entity\Activite implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Activite' . "\0" . 'ida', '' . "\0" . 'App\\Entity\\Activite' . "\0" . 'noma', '' . "\0" . 'App\\Entity\\Activite' . "\0" . 'typea', '' . "\0" . 'App\\Entity\\Activite' . "\0" . 'dispoa', '' . "\0" . 'App\\Entity\\Activite' . "\0" . 'descria', '' . "\0" . 'App\\Entity\\Activite' . "\0" . 'imagea'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Activite' . "\0" . 'ida', '' . "\0" . 'App\\Entity\\Activite' . "\0" . 'noma', '' . "\0" . 'App\\Entity\\Activite' . "\0" . 'typea', '' . "\0" . 'App\\Entity\\Activite' . "\0" . 'dispoa', '' . "\0" . 'App\\Entity\\Activite' . "\0" . 'descria', '' . "\0" . 'App\\Entity\\Activite' . "\0" . 'imagea'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Activite $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIda(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIda();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIda', []);

        return parent::getIda();
    }

    /**
     * {@inheritDoc}
     */
    public function getNoma(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNoma', []);

        return parent::getNoma();
    }

    /**
     * {@inheritDoc}
     */
    public function setNoma(?string $noma): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNoma', [$noma]);

        return parent::setNoma($noma);
    }

    /**
     * {@inheritDoc}
     */
    public function getTypea(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTypea', []);

        return parent::getTypea();
    }

    /**
     * {@inheritDoc}
     */
    public function setTypea(?string $typea): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTypea', [$typea]);

        return parent::setTypea($typea);
    }

    /**
     * {@inheritDoc}
     */
    public function getDispoa(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDispoa', []);

        return parent::getDispoa();
    }

    /**
     * {@inheritDoc}
     */
    public function setDispoa(?string $dispoa): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDispoa', [$dispoa]);

        return parent::setDispoa($dispoa);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescria(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescria', []);

        return parent::getDescria();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescria(?string $descria): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescria', [$descria]);

        return parent::setDescria($descria);
    }

    /**
     * {@inheritDoc}
     */
    public function getImagea(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImagea', []);

        return parent::getImagea();
    }

    /**
     * {@inheritDoc}
     */
    public function setImagea(?string $imagea): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImagea', [$imagea]);

        return parent::setImagea($imagea);
    }

}
