<?php

namespace ContainerGptdkFc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_8AmHkLFService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.8AmHkLF' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.8AmHkLF'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'activiteFavoris' => ['privates', '.errored..service_locator.8AmHkLF.App\\Entity\\Activitefavoris', NULL, 'Cannot autowire service ".service_locator.8AmHkLF": it references class "App\\Entity\\Activitefavoris" but no such service exists.'],
        ], [
            'activiteFavoris' => 'App\\Entity\\Activitefavoris',
        ]);
    }
}
