<?php

namespace ContainerGptdkFc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getActivitefavorisService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.8AmHkLF.App\Entity\Activitefavoris' shared service.
     *
     * @return \App\Entity\Activitefavoris
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.8AmHkLF": it references class "App\\Entity\\Activitefavoris" but no such service exists.');
    }
}
