<?php

namespace ContainerCFPhSxg;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MQ2naqaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.MQ2naqa' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.MQ2naqa'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'reservation' => ['privates', '.errored..service_locator.MQ2naqa.App\\Entity\\Reservationactivite', NULL, 'Cannot autowire service ".service_locator.MQ2naqa": it references class "App\\Entity\\Reservationactivite" but no such service exists.'],
            'reservationactivite' => ['privates', '.errored..service_locator.MQ2naqa.App\\Entity\\Reservationactivite', NULL, 'Cannot autowire service ".service_locator.MQ2naqa": it references class "App\\Entity\\Reservationactivite" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'reservation' => 'App\\Entity\\Reservationactivite',
            'reservationactivite' => 'App\\Entity\\Reservationactivite',
        ]);
    }
}
