#index:
#    path: /
#    controller: App\Controller\DefaultController::index
# Route pour le front-end

# config/routes.yaml



app_panier_index:
    path: /panier/
    controller: App\Controller\PanierController::indexx
    methods: GET

App\Controller\:
    resource: '../src/Controller/'
    type: annotation
# config/routes.yaml

