#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app_reservation_new_for_activity:
    path: '/reservation/new/{activityId}'
    controller: 'App\Controller\ReservationactiviteController::newForActivity'