<?php

namespace ContainerGa9ibIC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_H3LStiService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.H3L_sti' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.H3L_sti'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'reservationactivite' => ['privates', '.errored..service_locator.H3L_sti.App\\Entity\\Reservationactivite', NULL, 'Cannot autowire service ".service_locator.H3L_sti": it references class "App\\Entity\\Reservationactivite" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'reservationactivite' => 'App\\Entity\\Reservationactivite',
        ]);
    }
}
