<?php

namespace ContainerCEFTCZe;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WvsLMvBService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.WvsLMvB' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.WvsLMvB'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'repo' => ['privates', 'App\\Repository\\ActiviteRepository', 'getActiviteRepositoryService', true],
            'serializer' => ['privates', '.errored._q4zaSV', NULL, 'Cannot determine controller argument for "App\\Controller\\ActivitefavorisController::searchAjax()": the $serializer argument is type-hinted with the non-existent class or interface: "App\\Controller\\SerializerInterface". Did you forget to add a use statement?'],
        ], [
            'repo' => 'App\\Repository\\ActiviteRepository',
            'serializer' => '?',
        ]);
    }
}
