<?php

namespace ContainerCEFTCZe;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReservationactivite3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.MQ2naqa.App\Entity\Reservationactivite' shared service.
     *
     * @return \App\Entity\Reservationactivite
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.MQ2naqa": it references class "App\\Entity\\Reservationactivite" but no such service exists.');
    }
}
