<?php

namespace ContainerCdrK1xb;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReservationactiviteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator..BdxQPY.App\Entity\Reservationactivite' shared service.
     *
     * @return \App\Entity\Reservationactivite
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator..BdxQPY": it references class "App\\Entity\\Reservationactivite" but no such service exists.');
    }
}
