<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCFPhSxg\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCFPhSxg/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCFPhSxg.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCFPhSxg\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCFPhSxg\App_KernelDevDebugContainer([
    'container.build_hash' => 'CFPhSxg',
    'container.build_id' => 'df43c24d',
    'container.build_time' => 1714233959,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCFPhSxg');
