<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTIePxto\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTIePxto/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTIePxto.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTIePxto\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTIePxto\App_KernelDevDebugContainer([
    'container.build_hash' => 'TIePxto',
    'container.build_id' => '75a44a43',
    'container.build_time' => 1713012531,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTIePxto');
