<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHIL9xAr\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHIL9xAr/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHIL9xAr.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHIL9xAr\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHIL9xAr\App_KernelDevDebugContainer([
    'container.build_hash' => 'HIL9xAr',
    'container.build_id' => '69f6998b',
    'container.build_time' => 1713625124,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHIL9xAr');
