<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'app_activite_index' => [[], ['_controller' => 'App\\Controller\\ActiviteController::index'], [], [['text', '/activite/']], [], [], []],
    'app_activite_indexBack' => [[], ['_controller' => 'App\\Controller\\ActiviteController::indexBack'], [], [['text', '/activite/back']], [], [], []],
    'app_activite_new' => [[], ['_controller' => 'App\\Controller\\ActiviteController::new'], [], [['text', '/activite/new']], [], [], []],
    'app_activite_show' => [['ida'], ['_controller' => 'App\\Controller\\ActiviteController::show'], [], [['variable', '/', '[^/]++', 'ida', true], ['text', '/activite']], [], [], []],
    'app_activite_edit' => [['ida'], ['_controller' => 'App\\Controller\\ActiviteController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'ida', true], ['text', '/activite']], [], [], []],
    'app_activite_delete' => [['ida'], ['_controller' => 'App\\Controller\\ActiviteController::delete'], [], [['variable', '/', '[^/]++', 'ida', true], ['text', '/activite']], [], [], []],
    'base' => [[], ['_controller' => 'App\\Controller\\ExampleController::index'], [], [['text', '/base']], [], [], []],
    'baseBack' => [[], ['_controller' => 'App\\Controller\\ExampleController::indexBack'], [], [['text', '/baseBack']], [], [], []],
    'app_reservationactivite_index' => [[], ['_controller' => 'App\\Controller\\ReservationactiviteController::index'], [], [['text', '/reservationactivite/']], [], [], []],
    'app_reservationactivite_indexBack' => [[], ['_controller' => 'App\\Controller\\ReservationactiviteController::indexBack'], [], [['text', '/reservationactivite/back']], [], [], []],
    'app_reservationactivite_new' => [[], ['_controller' => 'App\\Controller\\ReservationactiviteController::new'], [], [['text', '/reservationactivite/new']], [], [], []],
    'app_reservationactivite_show' => [['idr'], ['_controller' => 'App\\Controller\\ReservationactiviteController::show'], [], [['variable', '/', '[^/]++', 'idr', true], ['text', '/reservationactivite']], [], [], []],
    'app_reservationactivite_edit' => [['idr'], ['_controller' => 'App\\Controller\\ReservationactiviteController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'idr', true], ['text', '/reservationactivite']], [], [], []],
    'app_reservationactivite_editBack' => [['idr'], ['_controller' => 'App\\Controller\\ReservationactiviteController::editBack'], [], [['text', '/editBack'], ['variable', '/', '[^/]++', 'idr', true], ['text', '/reservationactivite']], [], [], []],
    'app_reservationactivite_delete' => [['idr'], ['_controller' => 'App\\Controller\\ReservationactiviteController::delete'], [], [['variable', '/', '[^/]++', 'idr', true], ['text', '/reservationactivite']], [], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
];
